import type { Metadata } from "next";
import { clsx } from "clsx";

import PlausibleProvider from "next-plausible";

import { fonts } from "@/styles/fonts";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx(fonts.ADLaMDisplay.variable, fonts.SpaceMono.variable)}
    >
      <head>
        <PlausibleProvider domain="taoshi.io" />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
