import "normalize.css/normalize.css";
import "../styles/index.scss";

import type { Metadata } from "next";
import { clsx } from "clsx";

import { Space_Mono } from "next/font/google";
import localFont from "next/font/local";

const ADLaMDisplay = localFont({
  src: "../fonts/ADLaMDisplay-Regular.ttf",
  weight: "400",
  style: "normal",
  variable: "--font-adlam",
});

const SpaceMono = Space_Mono({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={clsx(ADLaMDisplay.variable, SpaceMono.variable)}>
      <body>{children}</body>
    </html>
  );
}
